{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "s2-lite.fullname" . }}
  labels:
    {{- include "s2-lite.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "s2-lite.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
    {{- if .Values.tls.enabled }}
    scheme: https
    tlsConfig:
      {{- if gt (len .Values.metrics.serviceMonitor.tlsConfig) 0 }}
      {{- toYaml .Values.metrics.serviceMonitor.tlsConfig | nindent 6 }}
      {{- else }}
      insecureSkipVerify: true
      {{- end }}
    {{- end }}
{{- end }}
